name: Generate Datas

on:
  workflow_dispatch: # execute manually
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

jobs:

  summary-cards:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          
  snake-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name:  ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish Snake Animation SVG
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  metrics-achievements:
    runs-on: ubuntu-latest
    steps:
      - name: Achievements metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.ACCESS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching threshold and secrets params

  metrics-github:
    runs-on: ubuntu-latest
    steps:
      - name: Github metrics
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
