name: My-Workflows

on:
  schedule: # Execute every 24 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:

    name: Generate Datas
    runs-on: ubuntu-latest
    steps:
      # Generate Summary Cards
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      
      # Generate Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GuillaumeFalourd
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Generate DEV.TO posts
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/guifalourd"
